#!/bin/sh
# gates-toolkit fragment: ReqGuard gate (blocking)
# Generated by gates-toolkit - do not edit; re-run setup-gates to regenerate.
# Registered as pre-commit entry 030-reqguard (mode=block).

# $0 is unreliable here (the dispatcher runs fragments via `sh -c "<cmd>" _ ...`),
# so resolve the repo root from git instead.
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
[ -n "$PROJECT_ROOT" ] || exit 0
GATES_DIR="$PROJECT_ROOT/.gates"
CHECK="$GATES_DIR/hooks/req-guard-check.sh"

# ⚠️ 与 sql-guard/java-guard 的 fail-open 不同：req-guard 是**安全机制**，
# 脚本缺失必须 fail-closed（拦截并提示初始化），否则门禁静默失效——
# "看起来在拦，实际没拦"是本工具最危险的失败模式。
if [ ! -f "$CHECK" ]; then
  echo "✗ ReqGuard 门禁脚本缺失（.gates/hooks/req-guard-check.sh），提交已被阻止。" >&2
  echo "  请先初始化门禁：req-guard init -p \"$PROJECT_ROOT\"" >&2
  echo "  如确需跳过本次：git commit --no-verify" >&2
  exit 1
fi

sh "$CHECK"
exit $?
